name: new_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.1
#  firebase_auth_ui: ^1.0.1
  google_maps_flutter: ^2.2.1
  uuid: ^3.0.4
  rxdart: ^0.27.4
  firebase_database: ^9.1.7
  firebase_core: ^1.24.0
  firebase_analytics: ^9.3.8
  google_maps_webservice: ^0.0.19
  geolocator: ^9.0.2
  plugin_platform_interface: ^2.1.3
  geocoding: ^2.0.5
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
 # flutter_google_places_hoc081098: ^1.1.0

  cloud_firestore: ^3.5.1
  query: ^2.0.0
  queries: ^0.1.14
  firebase: ^9.0.1
  shared_preferences: ^2.0.15
  get: ^4.1.4
  pinput: ^2.2.14
  firebase_auth: ^3.1.0
  flutter_plugin_android_lifecycle: ^2.0.4
#  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  async: ^2.8.1
  location_platform_interface: ^2.3.0
  dcdg: ^4.0.0
  geolocator_android: ^4.1.3
  firebase_messaging: ^13.1.0
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  permission_handler: ^10.1.0
  intl: ^0.17.0
  flutter_typeahead: ^4.1.1
 # flutter_google_places: ^0.3.0





  #  daily bus admin plugin...

  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  fl_chart: ^0.55.2
  data_table_2: ^2.0.3
  stacked: ^3.0.0








  #  flutter_polyline_points: ^1.0.0






  #  autocomplete_textfield: ^1.7.3
#  dropdownfield: ^1.0.3
#  flutter_dropdown: ^1.0.0+hotfix.1


#  location: ^4.3.0
#  flutter_google_places: ^0.3.0










 # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  permission: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_lints: ^2.0.1


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/imageUser.png
    - images/myBuss.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/5.png
    - images/6.png
    - images/7.png
    - images/journey.png
    - images/8.png
    - images/10.png
    - images/11.png
    - images/12.png
    - images/dailyBus.png



#    - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
